// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/contact-us": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/admin/registrations": {
    params: {};
  };
  "/services/ads-training-service": {
    params: {};
  };
  "/services/seo-training-service": {
    params: {};
  };
  "/services/web-maker": {
    params: {};
  };
  "/google-ads-service": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/contact-us" | "/blog" | "/blog/:slug" | "/admin/registrations" | "/services/ads-training-service" | "/services/seo-training-service" | "/services/web-maker" | "/google-ads-service";
  };
  "components/Layout.tsx": {
    id: "components/Layout";
    page: "/" | "/contact-us" | "/blog" | "/blog/:slug" | "/admin/registrations" | "/services/ads-training-service" | "/services/seo-training-service" | "/services/web-maker" | "/google-ads-service";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/contact-us.tsx": {
    id: "routes/contact-us";
    page: "/contact-us";
  };
  "routes/blog.tsx": {
    id: "routes/blog";
    page: "/blog";
  };
  "routes/blogDetail.tsx": {
    id: "routes/blogDetail";
    page: "/blog/:slug";
  };
  "routes/admin.registrations.tsx": {
    id: "routes/admin.registrations";
    page: "/admin/registrations";
  };
  "routes/services.ads-training-service.tsx": {
    id: "routes/services.ads-training-service";
    page: "/services/ads-training-service";
  };
  "routes/services.seo-training-service.tsx": {
    id: "routes/services.seo-training-service";
    page: "/services/seo-training-service";
  };
  "routes/services.web-maker.tsx": {
    id: "routes/services.web-maker";
    page: "/services/web-maker";
  };
  "routes/google-ads-service.tsx": {
    id: "routes/google-ads-service";
    page: "/google-ads-service";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "components/Layout": typeof import("./app/components/Layout.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/contact-us": typeof import("./app/routes/contact-us.tsx");
  "routes/blog": typeof import("./app/routes/blog.tsx");
  "routes/blogDetail": typeof import("./app/routes/blogDetail.tsx");
  "routes/admin.registrations": typeof import("./app/routes/admin.registrations.tsx");
  "routes/services.ads-training-service": typeof import("./app/routes/services.ads-training-service.tsx");
  "routes/services.seo-training-service": typeof import("./app/routes/services.seo-training-service.tsx");
  "routes/services.web-maker": typeof import("./app/routes/services.web-maker.tsx");
  "routes/google-ads-service": typeof import("./app/routes/google-ads-service.tsx");
};